blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/wsapi-chat/wsapi-dotnet/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
